import { ComponentItem } from './index';

export const typography: ComponentItem[] = [
  {
    id: 'terminal-typewriter',
    name: 'Terminal Output',
    description: 'Reveals text character by character with a blinking block.',
    category: 'Typography',
    new: true,
    code: {
      html: `<div class="terminal-text" id="typewriter"></div>`,
      css: `.terminal-text {
  font-family: 'Courier New', Courier, monospace;
  color: #10b981;
  font-size: 1.2rem;
  background: #000;
  padding: 16px;
  border-radius: 8px;
  border: 1px solid #333;
}
.cursor {
  display: inline-block;
  width: 10px; height: 1.2em;
  background: #10b981;
  vertical-align: bottom;
  animation: blink 1s step-end infinite;
  margin-left: 2px;
}
@keyframes blink {
  0%, 100% { opacity: 1; }
  50% { opacity: 0; }
}`,
      js: `const el = document.getElementById('typewriter');
const text = "> Initializing system...\\n> Access granted.";
let i = 0;

function typeWriter() {
  if (i < text.length) {
    const char = text.charAt(i);
    if (char === '\\n') {
      el.innerHTML = el.innerHTML.replace('<span class="cursor"></span>', '') + '<br>';
    } else {
      el.innerHTML = el.innerHTML.replace('<span class="cursor"></span>', '') + char;
    }
    el.innerHTML += '<span class="cursor"></span>';
    i++;
    setTimeout(typeWriter, Math.random() * 50 + 30);
  }
}
typeWriter();`
    }
  },
  {
    id: 'gradient-reveal',
    name: 'Gradient Sweep',
    description: 'Color gradient sweeps across text.',
    category: 'Typography',
    code: {
      html: `<h1 class="gradient-reveal">Stunning Visuals</h1>`,
      css: `.gradient-reveal {
  font-size: 4rem;
  font-weight: 900;
  background: linear-gradient(
    90deg,
    #52525b 0%,
    #fff 50%,
    #52525b 100%
  );
  background-size: 200% auto;
  color: transparent;
  -webkit-background-clip: text;
  background-clip: text;
  animation: shine 3s linear infinite;
}
@keyframes shine {
  to { background-position: 200% center; }
}`,
      js: ``
    }
  },
  {
    id: 'ai-reveal',
    name: 'AI Text Reveal',
    description: 'Staggered, glowing text reveal mimicking AI generation.',
    category: 'Typography',
    code: {
      html: `<div class="ai-text-container" id="ai-text-container">
  <!-- Content generated by JS -->
</div>`,
      css: `.ai-text-container {
  font-size: 1.5rem;
  line-height: 1.5;
  color: #fff;
  max-width: 600px;
}
.ai-word {
  display: inline-block;
  opacity: 0;
  transform: translateY(10px);
  filter: blur(10px);
  animation: ai-reveal 0.6s cubic-bezier(0.4, 0, 0.2, 1) forwards;
  margin-right: 0.3em;
  color: #a1a1aa;
}
.ai-word.highlight {
  color: #fff;
  text-shadow: 0 0 10px rgba(255, 255, 255, 0.5);
  transition: color 0.5s, text-shadow 0.5s;
}
@keyframes ai-reveal {
  100% {
    opacity: 1;
    transform: translateY(0);
    filter: blur(0);
  }
}`,
      js: `const container = document.getElementById('ai-text-container');
const text = "To be a complete library, you need to replace those placeholders and add components that modern design engineers actually want.";
const words = text.split(' ');

container.innerHTML = '';
words.forEach((word, i) => {
  const span = document.createElement('span');
  span.className = 'ai-word';
  span.textContent = word;
  span.style.animationDelay = \`\${i * 100}ms\`;
  
  // Flash white then settle to gray
  setTimeout(() => {
    span.classList.add('highlight');
    setTimeout(() => span.classList.remove('highlight'), 300);
  }, i * 100 + 400); // Trigger flash right as it resolves
  
  container.appendChild(span);
});`
    }
  },
  {
    id: 'stagger-fade',
    name: 'Staggered Fade',
    description: 'Letters fade in sequence.',
    category: 'Typography',
    code: {
      html: `<div class="stagger-container">
  <span>R</span><span>e</span><span>v</span><span>e</span><span>a</span><span>l</span>
</div>`,
      css: `.stagger-container { font-size: 3rem; font-weight: bold; }
.stagger-container span {
  opacity: 0;
  animation: fade-in 0.5s forwards;
}
.stagger-container span:nth-child(1) { animation-delay: 0.1s; }
.stagger-container span:nth-child(2) { animation-delay: 0.2s; }
.stagger-container span:nth-child(3) { animation-delay: 0.3s; }
.stagger-container span:nth-child(4) { animation-delay: 0.4s; }
.stagger-container span:nth-child(5) { animation-delay: 0.5s; }
.stagger-container span:nth-child(6) { animation-delay: 0.6s; }
@keyframes fade-in {
  to { opacity: 1; text-shadow: 0 0 10px rgba(255,255,255,0.5); }
}`,
      js: ``
    }
  },
  {
    id: 'glitch-text',
    name: 'Glitch Cyberpunk',
    description: 'Text that randomly distorts with RGB splitting on hover.',
    category: 'Typography',
    code: {
      html: `<h1 class="glitch" data-text="CYBERPUNK">CYBERPUNK</h1>`,
      css: `.glitch {
  font-size: 5rem;
  font-weight: bold;
  text-transform: uppercase;
  position: relative;
  color: white;
  letter-spacing: 5px;
}
.glitch::before, .glitch::after {
  content: attr(data-text);
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  opacity: 0;
}
.glitch:hover::before {
  left: 2px;
  text-shadow: -2px 0 red;
  clip: rect(24px, 550px, 90px, 0);
  animation: glitch-anim-2 3s infinite linear alternate-reverse;
  opacity: 1;
}
.glitch:hover::after {
  left: -2px;
  text-shadow: -2px 0 blue;
  clip: rect(85px, 550px, 140px, 0);
  animation: glitch-anim 2.5s infinite linear alternate-reverse;
  opacity: 1;
}
@keyframes glitch-anim {
  0% { clip: rect(72px, 9999px, 83px, 0); }
  20% { clip: rect(29px, 9999px, 16px, 0); }
  40% { clip: rect(54px, 9999px, 10px, 0); }
  60% { clip: rect(89px, 9999px, 94px, 0); }
  80% { clip: rect(20px, 9999px, 30px, 0); }
  100% { clip: rect(4px, 9999px, 91px, 0); }
}
@keyframes glitch-anim-2 {
  0% { clip: rect(65px, 9999px, 100px, 0); }
  20% { clip: rect(10px, 9999px, 14px, 0); }
  40% { clip: rect(23px, 9999px, 45px, 0); }
  60% { clip: rect(70px, 9999px, 80px, 0); }
  80% { clip: rect(40px, 9999px, 50px, 0); }
  100% { clip: rect(90px, 9999px, 12px, 0); }
}`,
      js: ``
    }
  },
  {
    id: 'scroll-driven-text',
    name: 'Scroll-Driven Reveal',
    description: 'Text that fades in bound to the scroll position using CSS animation-timeline.',
    category: 'Typography',
    code: {
      html: `<div class="scroll-container">
  <p class="scroll-instruction">Scroll down inside this box ↓</p>
  <div class="scroll-space"></div>
  <h2 class="scroll-reveal-text">Revealed by Scroll</h2>
  <div class="scroll-space"></div>
</div>`,
      css: `.scroll-container {
  height: 300px;
  width: 100%;
  overflow-y: scroll;
  position: relative;
  border: 1px solid #333;
  border-radius: 8px;
  background: #09090b;
}
.scroll-instruction {
  text-align: center;
  padding: 20px;
  color: #888;
}
.scroll-space {
  height: 400px;
}
.scroll-reveal-text {
  text-align: center;
  font-size: 3rem;
  color: #fff;
  /* Using CSS Scroll-Driven Animations API */
  animation: fade-scale auto linear both;
  animation-timeline: view();
  animation-range: entry 20% cover 50%;
}
@keyframes fade-scale {
  0% { opacity: 0; transform: scale(0.8) translateY(50px); filter: blur(10px); }
  100% { opacity: 1; transform: scale(1) translateY(0); filter: blur(0); }
}`,
      js: ``
    }
  },
  { id: 'split-text', name: 'Vertical Split', description: 'Text halves slide together.', category: 'Typography', code: { html: '<!-- implementation soon -->', css: '', js: '' } },
  { id: 'isometric-text', name: 'Isometric 3D', description: 'Shadow depth 3D text.', category: 'Typography', code: { html: '<!-- implementation soon -->', css: '', js: '' } },
  {
    id: 'neon-glow',
    name: 'Neon Flicker',
    description: 'Flickering neon sign text.',
    category: 'Typography',
    code: {
      html: `<h1 class="neon-text">OPEN</h1>`,
      css: `.neon-text {
  font-family: 'Arial', sans-serif;
  font-size: 5rem;
  font-weight: 900;
  color: #fff;
  text-shadow:
    0 0 7px #fff,
    0 0 10px #fff,
    0 0 21px #fff,
    0 0 42px #ff00de,
    0 0 82px #ff00de,
    0 0 92px #ff00de,
    0 0 102px #ff00de,
    0 0 151px #ff00de;
  animation: flicker 1.5s infinite alternate;
}
@keyframes flicker {
  0%, 18%, 22%, 25%, 53%, 57%, 100% { text-shadow: 0 0 7px #fff, 0 0 10px #fff, 0 0 21px #fff, 0 0 42px #ff00de, 0 0 82px #ff00de, 0 0 92px #ff00de; }
  20%, 24%, 55% { text-shadow: none; color: #555; }
}`,
      js: ``
    }
  },
  { id: 'wave-text', name: 'Jumping Wave', description: 'Individual letters jump in a wave.', category: 'Typography', code: { html: '<!-- implementation soon -->', css: '', js: '' } }
];
